### ISSUE TITLE
Zrobienie PQL i PKB

### ISSUE THREAD

**Issue by SiwyKot41** [wvffle/ATS-project-simple#10]
W jaki sposób ma działać PQL w naszym projekcie, w sensie parser działa chociażby tak że w main.py, gdy string jest w odpowiedni sposób parsowany, to nie jest zwracany żaden błąd. Czy PQL może działać tak, że do funkcji podamy fragment kodu do analizy, a jako drugi parametr zapytanie według którego zwrócone zostaną nam poszczególne linijki?

**Comment by SiwyKot41** [comment]
@wvffle

**Comment by wvffle** [comment]
koncowka `QL` w nazwie `PQL` oznacza `Query Language`, a to z kolei oznacza parser nastepnego jezyka. Jezeli w wykladach jest zaproponowane inne rozwiazanie, to mozemy je rozwazyc. To co Wy musicie napisac to jest Query Preprocessor czyli kawalek kodu ktory jest odpowiedzialny za poprawne wykonanie takiego stringa:
```
stmt s1, s2;
Select s1 such that Follows(s1, s2);
```

W MRce #11 macie implementacje drzewa AST, Query Preprocessor powinien odwolywac sie bezposrednio do drzewa AST. Operujac na drzewie AST mozecie bezproblemowo zaimplementowac `Follows` i `Parent` (razem z ich alternatywnymi wersjami) wedle definicji, jakie byly w wykladzie.

**Comment by wvffle** [comment]
@SiwyKot41 rozdziel prace miedzy wasza czworke

**Comment by Jaaaaaxi** [comment]
W jaki sposób ma działać PKB? Dajmy na to Follows ma wykrywać czy dwa stmt następują po sobie ale ma otrzymywać operacje jako parametry i np umieszczać je na liście i potem operować na niej ?

**Comment by SiwyKot41** [comment]
@wvffle nie uważam się za osobę kompetentą do tego by rozdzielać kto co ma robić, gdyż sam nie wiem, które zadanie jest najtrudniejsze. Póki co @Jaaaaaxi @KamiloSzcz  pracują nad PKB, a moim zadaniem jest zacząć PQL. Jednak wydaje mi się, że dokładny podział powinna wyznaczyć osoba, która najlepiej ogarnia temat. Wg mnie tą osobą jest @wvffle

**Comment by wvffle** [comment]
> W jaki sposób ma działać PKB? Dajmy na to Follows ma wykrywać czy dwa stmt następują po sobie ale ma otrzymywać operacje jako parametry i np umieszczać je na liście i potem operować na niej ?

Wytlumaczylem to dla @KamiloSzcz. @KamiloSzcz sprawdziles specyfikacje? Porsze, odpowiedz tu w issue jak to zamierzacie zaimplementowac. Mam nadzieje, ze @MParchan rowniez wam pomoze



> @wvffle nie uważam się za osobę kompetentą do tego by rozdzielać kto co ma robić, gdyż sam nie wiem, które zadanie jest najtrudniejsze.

Podzial ktorego dokonales jest dobry. Jak widzisz, jestes jak najbardziej kompetentny ;)

**Comment by wvffle** [comment]
@MParchan z racji, ze juz w miare wyzdrowiales, przydzielam Cie spowrotem do issue. @Jaaaaaxi i @KamiloSzcz, dzialajcie.
